name: weixin
on:
  workflow_dispatch:
  schedule: 
    # 代表国际标准时间，北京时间需要+8小时，代表北京时间上午9:15点运行
    - cron: '0 9 * * 1-5'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.12.0
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.0

      - name: 设置时区为 Asia/Shanghai
        run: |
          sudo apt-get install -y tzdata
          sudo ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
          sudo dpkg-reconfigure -f noninteractive tzdata

      - name: 安装依赖包
        run: |
          python -m pip install --upgrade pip
          pip3 install -r requirements.txt

      - name: 运行 Python 脚本
        run: |
          python3 main.py
